### ISSUE TITLE
Possible problem with gene names from Panther pipeline 

### ISSUE THREAD

**Issue by pgaudet** [pantherdb/db-PAINT#1]
https://github.com/geneontology/amigo/issues/475

From @valwood

> another oddity with names (possibly from Panther pipeline)
I noticed whilst checking these
geneontology/helpdesk#99
Sometimes when you search on a human name, you see a gene name "A3GALT2 (1 of many)"
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:H2UKJ8
These seem to be assigned by some GO pipeline because they don't come from the UniProt entry
http://www.uniprot.org/uniprot/H2UKJ8
Until genes are "officially" names by a naming authority, we really shouldn't transfer names. This one should have the unique currently assigned systematic name, which is
Gene LOC101078261 (not very friendly but this is what we should use). We definitely should not be transferring human names to fish... and even more so one human name to multiple fish genes.

Another comment in that ticket: 
> This is quite a big issue for usability.
(GO should never assign gene symbols....)
GAF requirement:
Column | Content | Required? | Cardinality | Example
3 | DB Object Symbol | required | 1 | PHO3
"A3GALT2 (1 of many)" might be added so that the file conforms to the requirement to have a unique gene object symbol? (see above).
I'm guessing that it goes "A3GALT2 (1 of many)" , "A3GALT2 (2 of many)" etc. to ensure cardinality "1". It is difficult to know because the part of these labels in parentheses does not appear to be searchable in AmigGO search.
The rule of thumb is i) all genes have a systematic name. ii) The systematic name is the "official name" until a "gene symbol" is assigned by the relevant naming authority.

>GO Docs appear to agree with this
"DB Object Symbol (column 3)
a (unique and valid) symbol to which DB object ID is matched
can use ORF name for otherwise unnamed gene or protein"
Then
"if gene products are annotated, can use gene product symbol if available, or many gene product annotation entries can share a gene symbol this field is mandatory, cardinality 1"
(although this sentence does not make complete sense?)
"The DB Object Symbol field should be a symbol that means something to a biologist wherever possible (a gene symbol, for example). It is not an ID or an accession number (DB object ID [column 2] provides the unique identifier), although IDs can be used as a DB object symbol if there is no more biologically meaningful symbol available (e.g., when an unnamed gene is annotated)."
ORF name is synonymous with "systematic name", == name assigned from the sequencing project (maybe this could be clearer).

**Comment by huaiyumi** [comment]
We followed the format of the legacy PAINT GAFs located on svn. It maybe time to put together a document about this.

**Comment by ValWood** [comment]
This problem seems to be resolved?

**Comment by huaiyumi** [comment]
OK I will close it.
