### ISSUE TITLE
Remove families with no EXP annotations from "Get unlocked and non-manually curated books" menu

### ISSUE THREAD

**Issue by pgaudet** [pantherdb/db-PAINT#10]
Hello, 

From the menu "Get unlocked and non-manually curated books", could you filter out those with no experimental annotations? 

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/4782928/67078608-e66d8580-f191-11e9-88f3-7d30531b0a9b.png">

Thanks, Pascale

**Comment by mugitty** [comment]
Once the system displays the unlocked and non-manually curated books, click on column "Experimental" in the title bar to sort by books with and without experimental evidence.
