### ISSUE TITLE
IBD propagation of IBA to leaf nodes with conflicting qualifier

### ISSUE THREAD

**Issue by mugitty** [pantherdb/db-PAINT#13]
PAINT Implementation for https://github.com/geneontology/paint/issues/54
1.	When a leaf gene has an experimental annotation consistent with the ancestral IBD annotation (meaning IBD is to the same or more general term in the experimental annotation with identical qualifier), it will receive an IBA.
2.	When a leaf gene has an experimental annotation with a conflict NOT qualifier to the ancestral IBD annotation, it should not receive an IBA.
3.	When a leaf gene has an experimental annotation with a conflict “contribute_to” or “colocalized_to” qualifier to the ancestral IBD annotation, it will still receive an IBA for the moment. Meanwhile, there is an effort to clean up the experimental annotations that contain those two qualifiers in GO. Once they are fixed, the leaf gene should not receive an IBA in this situation.

**Comment by dustine32** [comment]
Just noting I also have a ticket to handle this in the IBA propagation script:

https://github.com/pantherdb/fullgo_paint_update/issues/39

**Comment by mugitty** [comment]
Completed
