### ISSUE TITLE
In Curation database (V15), node organism relationship is incomplete.

### ISSUE THREAD

**Issue by mugitty** [pantherdb/db-PAINT#24]
This impacts PAINT output of IBA information with Taxon ids and also Taxonomy constraints rules

select * from organism where classification_version_sid = 27 and short_name = 'SACS2'; 

Returns 1 record.

select * from node where classification_version_sid = 27 and public_id like 'PTN000486337'; 

Returns 1 record

Query to retrieve node to organism information
select n.accession, n.public_id, o.organism
from node n, node_organism no, organism o
where n.CLASSIFICATION_VERSION_SID = 27  and n.accession like 'PTHR10000%'
and n.node_id = no.node_id and no.organism_id = o.organism_id and n.OBSOLESCENCE_DATE is null;

No records are returned for the following query
select n.accession, n.public_id, o.organism
from node n, node_organism no, organism o
where n.CLASSIFICATION_VERSION_SID = 27  and n.accession like 'PTHR10000%' and n.public_id like 'PTN000486337'
and n.node_id = no.node_id and no.organism_id = o.organism_id and n.OBSOLESCENCE_DATE is null;

**Comment by dustine32** [comment]
Good catch @mugitty! I initially thought this was SACS2-specific since we've had some problems with its 5-letter code change, but looks like `node_organism` is missing joins for all leaf nodes.

When loading this leaf data, I think I'm joining the 5-letter code (e.g. `MOUSE`, `SACS2`) to the wrong `organism` column.

**Comment by dustine32** [comment]
Sigh. It is `SACS2`-specific. All other leaf species are loaded. At least I'll only have to load one species.

**Comment by dustine32** [comment]
@mugitty K, I've added these 1874 `SACS2` entries into the Curation DB on panthertestdb for testing. Let me know when you want me to add them to Curation prod.

**Comment by mugitty** [comment]
@dustine32 , you can add to Curation prod whenever convenient

**Comment by dustine32** [comment]
Great! Just loaded them to prod.

**Comment by mugitty** [comment]
Thanks
