### ISSUE TITLE
Curator PMID evidence for IKR/IRD should be added for the following trees.

### ISSUE THREAD

**Issue by mugitty** [pantherdb/db-PAINT#25]
PTHR22573:AN12,   PTN002731341 - Term GO:0004614 - PMID:8631316 

PTHR11943:AN20, PTN000235352 - Term GO:0033499 - PMID:21075050 

PTHR11177:AN171, PTN000126567 Term GO:0004568 - PMID:11553626 

PTHR11177:AN312, PTN002597553 Term GO:0004568 - PMID:18342251 

PTHR11177:AN312, PTN002597553 Term GO:0008061 - PMID:18342251

**Comment by huaiyumi** [comment]
I manually added those PMIDs to the annotation.
